### PR TITLE
WIP: Additional plumping messages

### PR DESCRIPTION
**Pull request by mikelodder7**
Initial stab at admin messages for DIDs

### CODE REVIEW

**Comment by dbluhm** [comment]
I know it's nitpicky but can we clean up the git history a bit? If it's showing up that way because my branch is out of date with upstream, I'll fix that tomorrow

**Comment by mikelodder7** [comment]
I rebased @TelegramSam's branch onto yours and worked from there. So that's why you see that.

**Comment by dbluhm** [comment]
I muddied the water a bit; Sam's branch was merged upstream and I rebased this branch on master. We need your changes to cleanly sit on top of mine.

**Comment by dbluhm** [comment]
I committed your changes to my branch through patches; those additions aren't reflected here but you can check them out on the `feature/admin-messages` branch.

**Pull request closed without merging**
